#!/bin/bash

set -e
basedir=$(dirname "$(readlink -f "$0")")

"$basedir/install-apt-packages"

sudo "$basedir/install-nodejs-4.x"

# link dotfiles
for filename in "$basedir/dotfiles/".[^.]*; do
	ln -svf "$filename" ~
done

# install vim setup
~/.vim/install

